name: Code heath

on: [push, pull_request]

jobs:
  check-ruff:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Run tests without the package installed
      run: |
        pip install ruff -U -q
        ruff . --line-length=120
